apa512/clj-rethinkdb

src/rethinkdb/query.clj

Removes a warning when using Clojure 1.7.0.

Exclude "update" from clojure.core

---

README.md

I've added some examples which demonstrate usage in a number of cases.
If that's ok, I can also write some introductory docs on differences from other ReQL implementations, such as that (get-all) *always* takes a vector of keys, or that you always use get-field to access sub-fields.

expand examples to include more complex usage cases

---

project.clj
src/rethinkdb/core.clj
src/rethinkdb/net.clj
test/rethinkdb/connection_test.clj
test/rethinkdb/core_test.clj

Each connection now has a dedicated reader and writer core.async go block for serially reading/writing the socket. This way, a connection can be used by many threads without worry that they will adversely affect each other.
There is a minor performance penalty to connecting and disconnecting connections, as the core.async resources need to be created and destroyed too (measured at approx. 7% slower than before), but no measurable performance penalty was observed for the actual use of the connection.
Note that this PR adds a dependency on core.async.

Fixed thread-safety issues with connection

---

src/rethinkdb/query.clj

This is helpful for using an implicit database specified in the connection, ala #38.

Add new arity for table to use default database

---

src/rethinkdb/query.clj
test/rethinkdb/core_test.clj

Per the [docstring][1]:
> By default RethinkDB will ignore documents where a specified field is missing.
> Passing ```{:default (r/error)}``` as an optional argument will cause any
> non-existence error to raise an exception.
Currently, something like...
```clojure
(r/filter sq predicate {:default true})
```
...throws an exception:
> Wrong number of args (3) passed to: query/filter
[1]: https://github.com/apa512/clj-rethinkdb/blob/fb1423fafc6cc4c5e487d744f40c424e54ba3882/src/rethinkdb/query.clj#L180-L182

Update #'rethinkdb.query/filter to allow optargs

---

project.clj
src/rethinkdb/core.clj
test/rethinkdb/connection_test.clj
test/rethinkdb/core_test.clj

This is a pretty subtle bug, you will only run into it when you try to close a connection which has queries outstanding (e.g. changefeeds) using the `.close` method on the Connection. Before this PR there were two subtly different code paths that a closing connection could take:
1. Calling the close function in `rethinkdb.core` will deref `conn` (which is a Connection that implements `deref` to deref it's internal `conn` atom) and destructure the keys of the internal `conn` atom. 
* When running `send-stop-query` on every outstanding query, we pass the Connection. 
* Deeper in the call stack at `send-query`, we access the connection atom (without derefing it) by calling **`(:conn conn)` on the record**. 
* We do our `swap!` to remove the `:waiting` token from the set and continue.
2. …

Fix close method on Connection to use `this`

---

README.md
src/rethinkdb/core.clj
src/rethinkdb/query.clj
test/rethinkdb/connection_test.clj
test/rethinkdb/core_test.clj

It is often a pain to have to import the `rethinkdb.core` namespace just to make a connection. This PR imports the connect function into the `rethinkdb.query` ns which is the most common ns for API consumers to be using.
I wasn't keen on using something like Potemkin for a single function, sing out if you've got alternative approaches or have an issue with this, otherwise I'll merge this in a few days.

Import `connect` into query, connect docstring improvements

---

CHANGELOG.md
src/rethinkdb/net.clj
test/rethinkdb/core_test.clj

- Fix handling of CONTINUE and STOP queries. Global optargs from the db
connection were being appended to every query that was being sent if
the db parameter was set on the connection. START queries have two
elements in the vector: query type (START), and query. However
CONTINUE and STOP queries only have a single query type in the vector, so
the global optargs were getting appended as the second element in
these vectors. This caused RethinkDB to throw an error as we weren't
sending a valid query.
- Update changelog
- Add failing tests that pass with this fix.
To avoid these kinds of bugs in the future, it could be good to turn the query vector into a map with named elements.

Fix CONTINUE and STOP queries with implicit DB

---

CHANGELOG.md
src/rethinkdb/query.clj
test/rethinkdb/core_test.clj

This change makes it easier to isolate failing tests and to create new tests.
- Split the one large deftest into many smaller deftests
- Add fixtures to recreate pokedex table between every test
- Remove `run` and `db-run` command from core-test ns
- Remove global `conn`, each test now creates its own connection
Add arity for table and db operations without DB, the new arities will use the implicit DB from the connection.
- Add documentation for database priority to ns docstring
- Update docstrings on functions to reference priority docs in ns docstring
Arities modified on
- table-drop
- table-list
table-create was left as I wasn't yet sure how to handle the optargs with two arities.

Refactor tests, add table arities

---

project.clj
src/rethinkdb/core.clj
src/rethinkdb/net.clj
src/rethinkdb/query.clj
src/rethinkdb/utils.clj

This fixes almost all reflection warnings in clj-rethinkdb, except for reflections done by libraries and Protocol Buffer interop (this will be fixed in https://github.com/apa512/rethinkdb-protobuf/pull/3).

Fix reflection warnings

---

CHANGELOG.md
project.clj
src/rethinkdb/core.clj
src/rethinkdb/net.clj
test-resources/logback-test.xml

Library users will need to provide a clojure.tools.logging compatible logger to see these logs, we don't bundle logback so we can let the user choose. Similarly, they will need to provide their own logging config, as our one is in test-resources and won't be packaged in the JAR.

Add clojure.tools.logging and logging statements

---

CHANGELOG.md
src/rethinkdb/query.cljc
test/rethinkdb/core_test.clj

Simple indexes are based on the value of a single field, and can be created by passing the field name as the name of the index.
N.B. You can create an index on a field that doesn't 'exist', because RethinkDB has no notion of a schema and therefore no ability to tell whether a field will be present in the future or an index is 'valid' when it is created.
I'm not 100% happy with the switching on whether `func` is nil, but I don't really see any other way to accomplish this while keeping optargs optional. Happy to hear other ideas though.
Fixes #83

Modify index-create to allow simple indexes

---

CHANGELOG.md
README.md
project.clj

We don't want people to get confused between the official Java RethinkDB driver and this driver.
This probably shouldn't be merged until we're ready to release the next version, as it changes the URL and SVG of Clojars links.
Fixes #92

Change Group ID from rethinkdb to com.apa512

---

CHANGELOG.md
src/rethinkdb/net.clj
test/rethinkdb/core_test.clj

It is sometimes difficult for people to distinguish between an exception
thrown in the client library, and an exception from the server which is
sent back and thrown by the client library. This change prefixes
serverside exceptions to make this distinction clearer.
Fixes #95, fixes #94

Prefix RethinkDB server exceptions with `RethinkDB server: `

---

src/rethinkdb/net.clj
src/rethinkdb/utils.cljc
test/rethinkdb/core_test.clj

RethinkDB requires Drivers to "Serialize the query as UTF8-encoded JSON"

UTF-8 strings

---

README.md

- It took me quite some time to understand how to do an upsert that does not override
some fields in the previous document. And keeping the query atomic.
- Share back the result.

README: Add upsert with created/updated time example

---

src/rethinkdb/query_builder.cljc

Reflection warning, clj-rethinkdb/src/rethinkdb/query_builder.cljc:48:19 - call to java.lang.String ctor can't be resolved.

Add type hint to remove reflection warning

---

src/rethinkdb/query.cljc

Here is a patch for `rethinkdb.query`.
It wraps `IllegalArgumentException` in a reader conditional

Add reader conditional around IllegalArgumentException

---

src/rethinkdb/net.clj
test/rethinkdb/async_test.clj

- Extract logic into async-query?
- Add tests to cover all possible combinations of query opts and conn opts
- Fix bug when `opts={}` and `conn={:async? true}`, query would be run synchronously.

Extract logic for whether a query is async or not

---

src/rethinkdb/query_builder.cljc
test/rethinkdb/core_test.clj

clj-time's to-epoch function returns the number of seconds since epoch,
which truncates the milliseconds of DateTime. Use to-long, which returns
milliseconds since epoch, and divide by 1000 in order to properly format
this number

Persist milliseconds of DateTimes

---

README.md

The link for Javascript docs has been used twice.

Fix link for RethinkDB official docs

---

test/rethinkdb/joins_test.clj

This test as written has mis-aligned parens and doesn't actually check
equality.

[tests] Fix a test
